### ISSUE TITLE
Change scale to fit to stretch to fill for image in tiles.

### ISSUE THREAD

**Issue by bibinjacobpulickal** [dblock/ARTiledImageView#18]
Last row and last column tiles are being scaled to fit. I have tiles of 512x512. The resolution of whole images are not multiples of 512 i.e, whole image is of resolution 1030x1030. Therefore, there are 9 tiles. last column tiles in server are in 512x512 by adding a black portion to the rest of the image portion. I need the last image to be in stretch to fill. The image that I get from server should be drawn from 1024 to 1536. I'm not sure if you would understand the situation. But I've added two images that show this issue. That show the border before tiles are loaded and after tiles are load. The last tiles get shrunken.

![Before tiles are rendered](https://user-images.githubusercontent.com/26866256/31173406-f50664b6-a924-11e7-846f-677d9382d84c.png)
![after tiles are rendered](https://user-images.githubusercontent.com/26866256/31173448-2f400a56-a925-11e7-9478-50104fa5baa1.png)

**Comment by dblock** [comment]
Stretch to fill is a feature request. Please feel free to contribute.

**Comment by bibinjacobpulickal** [comment]
Any ideas on how I could achieve this?

**Comment by dblock** [comment]
All the drawing happens [here](https://github.com/dblock/ARTiledImageView/blob/master/Classes/ARTiledImageView.m#L61) so in theory you could do stretch math there.

**Comment by bibinjacobpulickal** [comment]
Achieved this by removing [this](https://github.com/dblock/ARTiledImageView/blob/master/Classes/ARTiledImageView.m#L112) line.

**Comment by dblock** [comment]
@bibinjacobpulickal If you want to get help here you really need to start turning your questions into something that's useful for this project. Just hacking on a fork is a bad long term strategy, please spend some time to contribute well built features with tests and documentation back.
